"""TikHub 响应解析(纯解析,无 HTTP)。原 parsers.py(609 行)按平台拆成三块,
这里原样再导出,调用方仍可 ``from app.blogger_distillation.tikhub_client.parsers import X``。

- :mod:`.common` —— 平台无关的取值 / 计数 / 时间 / 递归查找原语
- :mod:`.xhs`    —— 小红书:链接解析、笔记列表分页、互动数、类型判定
- :mod:`.douyin` —— 抖音:链接、用户信息、视频详情 / 列表、评论
"""

from app.blogger_distillation.tikhub_client.parsers.common import (
    dig,
    first_bool,
    first_bool_recursive,
    first_int,
    first_str,
    parse_count,
    parse_timestamp,
    recursive_find,
    unwrap_payload,
)
from app.blogger_distillation.tikhub_client.parsers.douyin import (
    extract_douyin_comments,
    extract_douyin_video_page,
    first_url_from_douyin_url_model,
    normalize_douyin_detail_payload,
    normalize_douyin_user_info,
    normalize_douyin_video_item,
    normalize_douyin_video_obj,
    parse_douyin_profile_link,
)
from app.blogger_distillation.tikhub_client.parsers.xhs import (
    CURSOR_KEYS,
    HAS_MORE_KEYS,
    PAGE_CURSOR_KEYS,
    clean_page_cursor,
    collect_metric_sources,
    collect_note_ids,
    detect_note_type,
    extract_container_items,
    extract_interaction_counts,
    extract_note_page,
    extract_xsec_token,
    find_best_note_container,
    find_comment_items,
    find_container_cursor,
    find_cursor,
    find_index,
    find_lists,
    find_note_candidates,
    find_page_area,
    find_payload_page_cursor,
    find_user_id,
    first_count,
    is_note_like_cursor_node,
    normalize_feed_item,
    parse_xhs_note_link,
    parse_xhs_profile_link,
    score_note_page,
)

__all__ = [
    "unwrap_payload",
    "first_str",
    "first_int",
    "parse_count",
    "dig",
    "recursive_find",
    "parse_timestamp",
    "first_bool",
    "first_bool_recursive",
    "parse_douyin_profile_link",
    "normalize_douyin_user_info",
    "extract_douyin_video_page",
    "normalize_douyin_video_item",
    "normalize_douyin_video_obj",
    "normalize_douyin_detail_payload",
    "extract_douyin_comments",
    "first_url_from_douyin_url_model",
    "parse_xhs_profile_link",
    "parse_xhs_note_link",
    "extract_note_page",
    "HAS_MORE_KEYS",
    "CURSOR_KEYS",
    "PAGE_CURSOR_KEYS",
    "score_note_page",
    "find_best_note_container",
    "extract_container_items",
    "normalize_feed_item",
    "extract_xsec_token",
    "find_container_cursor",
    "find_payload_page_cursor",
    "is_note_like_cursor_node",
    "clean_page_cursor",
    "collect_note_ids",
    "extract_interaction_counts",
    "collect_metric_sources",
    "first_count",
    "find_note_candidates",
    "find_comment_items",
    "find_lists",
    "find_cursor",
    "find_index",
    "find_page_area",
    "find_user_id",
    "detect_note_type",
]
