"""Pydantic request/response schemas, split by domain.

Re-exported here so existing ``from app.schemas import X`` imports keep working.
"""

from app.schemas.admin import (
    AdminTaskRead,
    AdminTenantRead,
    ConfigFieldView,
    ConfigGroupView,
    ConfigUpdate,
    ConfigView,
    CostByKey,
    CostEventRead,
    CostSummary,
    ModelPrices,
    PasswordReset,
    QueueHealth,
)
from app.schemas.article import ArticleRead, ArticleUpdate, DashboardRead
from app.schemas.audit import (
    AccountAuditCreate,
    AccountAuditReport,
    AccountAuditRunRead,
    AppraiseCreate,
    AppraisalIntentContextRequest,
    AppraisalIntentContextResult,
    AppraisalIntentQuestion,
    AppraisalIntentSuggestRequest,
    AppraisalIntentSuggestResult,
    SelfDiagnoseCreate,
)
from app.schemas.benchmark import (
    BenchmarkIntent,
    BenchmarkRecommendationRunRead,
    CandidateScore,
    EvaluateRequest,
    EvaluateResult,
    RecommendRequest,
)
from app.schemas.blogger import (
    BloggerCollectRequest,
    BloggerUrlCollectRequest,
    BloggerCollectionRunRead,
    BloggerDistillationRunRead,
    BloggerDistillRequest,
    BloggerDossierRead,
    CollectEstimate,
    DossierPoolSyncRequest,
    BloggerFavoriteUpdate,
    BloggerPostRead,
    BloggerPostsDeleteRequest,
    BloggerProfileCreate,
    BloggerProfileRead,
    BloggerProfileUpdate,
    BloggerSearchResultRead,
    BloggerSkillRead,
)
from app.schemas.news import NewsItemRead, NewsItemUpdate, NewsSourceRead
from app.schemas.settings import SettingRead, SettingUpdate
from app.schemas.task import OperationTaskEventRead, OperationTaskRead
from app.schemas.tenant import AdminUserCreate, AdminUserRead, CurrentUserRead, TenantRead
from app.schemas.workspace import (
    ContentGroupRead,
    ContentGroupUpdate,
    ContentProfileRead,
    ContentProfileUpdate,
    LayoutSettingsRead,
    LayoutSettingsUpdate,
    PublishingSettingsRead,
    PublishingSettingsUpdate,
    WeChatAccountRead,
    WeChatAccountUpdate,
    WorkspaceConfigRead,
    WorkspaceConfigUpdate,
)
from app.schemas.xhs import (
    XhsPublishPackageCreate,
    XhsPublishPackageDraftRead,
    XhsPublishPackageRead,
    XhsPublishPackageSave,
    XhsTopicIdeaRead,
    XhsTopicIdeaRequest,
    XhsTopicIdeaResponse,
)

__all__ = [
    "ConfigView",
    "ConfigGroupView",
    "ConfigFieldView",
    "ConfigUpdate",
    "AdminTaskRead",
    "QueueHealth",
    "AdminTenantRead",
    "PasswordReset",
    "CostEventRead",
    "CostByKey",
    "CostSummary",
    "ModelPrices",
    "TenantRead",
    "CurrentUserRead",
    "AdminUserRead",
    "AdminUserCreate",
    "ContentProfileRead",
    "ContentProfileUpdate",
    "ContentGroupRead",
    "ContentGroupUpdate",
    "WeChatAccountRead",
    "WeChatAccountUpdate",
    "LayoutSettingsRead",
    "LayoutSettingsUpdate",
    "PublishingSettingsRead",
    "PublishingSettingsUpdate",
    "WorkspaceConfigRead",
    "WorkspaceConfigUpdate",
    "NewsItemRead",
    "NewsItemUpdate",
    "NewsSourceRead",
    "ArticleRead",
    "ArticleUpdate",
    "DashboardRead",
    "OperationTaskRead",
    "OperationTaskEventRead",
    "AccountAuditCreate",
    "AccountAuditReport",
    "AccountAuditRunRead",
    "AppraiseCreate",
    "AppraisalIntentContextRequest",
    "AppraisalIntentContextResult",
    "AppraisalIntentQuestion",
    "AppraisalIntentSuggestRequest",
    "AppraisalIntentSuggestResult",
    "SelfDiagnoseCreate",
    "BenchmarkIntent",
    "CandidateScore",
    "RecommendRequest",
    "EvaluateRequest",
    "EvaluateResult",
    "BenchmarkRecommendationRunRead",
    "SettingRead",
    "SettingUpdate",
    "BloggerProfileCreate",
    "BloggerProfileUpdate",
    "BloggerFavoriteUpdate",
    "BloggerProfileRead",
    "BloggerSearchResultRead",
    "BloggerDistillRequest",
    "BloggerCollectRequest",
    "BloggerUrlCollectRequest",
    "CollectEstimate",
    "BloggerDossierRead",
    "DossierPoolSyncRequest",
    "BloggerPostRead",
    "BloggerPostsDeleteRequest",
    "BloggerCollectionRunRead",
    "BloggerDistillationRunRead",
    "BloggerSkillRead",
    "XhsPublishPackageCreate",
    "XhsPublishPackageDraftRead",
    "XhsPublishPackageSave",
    "XhsTopicIdeaRequest",
    "XhsTopicIdeaRead",
    "XhsTopicIdeaResponse",
    "XhsPublishPackageRead",
]
